apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ked.name" . }}
  labels:
    {{- include "ked.labels" . | nindent 4 }}
data:
  config.yaml:  {{ toYaml .Values.configmap | b64enc | quote  }}
