configmap:
    jenkins_url: https://jenkins.acme.corp
    slack:
        app_token: xapp-0-aaaa-bbb-cccc
        bot_token: xoxb-aaaa-bbb-cccc
        channel: C1234567890
        msg_max_size: 4000
    repository:
        - name: bitbucket
          url: https://api.bitbucket.org/2.0/repositories/acme
          username: acme-ked
          token: token12345
